
---

- name: install required packages
  package:
      name: "{{ item }}"
      state: present
  become: true
  become_user: root
  with_items:
      - tmux

- name: link tmuxconf
  file:
      src: "{{ role_path }}/files/tmux.conf"
      dest: "~/.tmux.conf"
      state: link
